apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: rucio-frdf
spec:
  kafka:
    version: 3.5.0
    replicas: 5
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.5"
    storage:
      type: persistent-claim
      size: 50Gi
      deleteClaim: false
      class: kafka-local-storage
  zookeeper:
    replicas: 5
    storage:
      type: persistent-claim
      size: 50Gi
      deleteClaim: false
      class: zookeper-local-storage
  entityOperator:
    topicOperator: {}
    userOperator: {}
