apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv
  labels:
    namespace: rucio 
    pvc_name: rucio-frdf-kafka-data-0
spec:
  capacity:
    storage: 50Gi 
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kafka-local-storage
  local:
    path: /data/kafka/kafka 
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - ccqserv222

